dist: trusty
language: python
addons:
  apt:
    packages:
      - cloc
python: 3.6
branches:
  only:
    - master
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py36
install:
  - pip install tox pytest pytest-cov pep8
script:
  tox -e $TOX_ENV
after_success:
  - make loc