language: python
python: 3.6
dist: trusty
branches:
  only:
    - master
env:
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=py36
install:
    - pip install tox pytest pytest-cov
script:
    tox -e $TOX_ENV